name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # わざと古い major に固定（Dependabot が更新PRを作りやすい）
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16" # 古い固定（例）
          cache: "npm"

      - run: npm ci
      - run: npm test
